version: '2.1'

services:
  mysql:
    image: mysql:8
    mem_limit: 512m
    restart: always
    network_mode: bridge
    labels:
      - triton.cns.services=bridge-mysql
    expose:
      - 3306
    env_file:
      - _env_mysql

  consul:
    image: autopilotpattern/consul:1.0.0r43
    command: >
      /usr/local/bin/containerpilot
    env_file:
      - _env_consul
    restart: always
    mem_limit: 512m
    network_mode: bridge
    labels:
      - triton.cns.services=bridge-consul
    expose:
      - 9090
      - 8500

  prototype:
    image: d0cker/minio-proto:0.0.24
    restart: always
    mem_limit: 1g
    network_mode: bridge
    labels:
      - triton.cns.services=bridge
    env_file:
      - _env
      - _env_consul
      - _env_mysql
    environment:
      - CONSUL=consul
      - MYSQL_HOST=mysql
      - NODE_ENV=development
    links:
      - consul:consul
      - mysql:mysql
    ports:
      - 80:80
      - 443:443
