mysql:
  image: mysql:8
  mem_limit: 512m
  restart: always
  expose:
    - 3306
  env_file:
    - _env_mysql

consul:
  image: autopilotpattern/consul:1.0.0r43
  command: >
    /usr/local/bin/containerpilot
  environment:
   - CONSUL_DEV=1
   - CONSUL=localhost
  restart: always
  mem_limit: 512m
  ports:
    - 9090:9090
    - 8500:8500

prototype:
  image: d0cker/minio-proto:0.0.24
  restart: always
  mem_limit: 1g
  env_file:
    - _env
    - _env_mysql
  environment:
    - PORT=8080
    - CONSUL=consul
    - CONSUL_AGENT=1
    - MYSQL_HOST=mysql
    - BASE_URL=http://localhost
    - DOMAIN=localhost
  links:
    - consul:consul
    - mysql:mysql
  ports:
    - 80:80
    - 443:443
